### ISSUE TITLE
Fail: go get dasa.cc/htm

### ISSUE THREAD

**Issue by comaldave** [dskinner/htm#3]
### to duplicate
```
go get dasa.cc/htm
```

### unexpected response
```
go: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/david/go/pkg/mod/cache/vcs/fbcc56510c11784193fcc3d63ff3ad1e55252b679327c036f46772c8a6b10bf5: exit status 128:
        error: RPC failed; HTTP 301 curl 22 The requested URL returned error: 301
        fatal: the remote end hung up unexpectedly
```

**Comment by dskinner** [comment]
azul3d.org/lmath.v1 is the issue as this no longer exists. The only thing used from there is the Vec3 struct so this could just be inlined here. More preferably perhaps is to use this instead for the vec type across many packages:
https://pkg.go.dev/golang.org/x/image@v0.21.0/math/f64

this is what I do elsewhere though I think it changes the semantics of htm internals since lmath.Vec3 used fields of struct and x/image/math/f64 uses an array.

**Comment by comaldave** [comment]
I understand link rot.

I was having ISP problems as well. It is hard to diagnose problems when you have two issues at the same time.

I shall proceed with your suggestion.

**Comment by dskinner** [comment]
this should work now. I found the source on github and linked directly to it and ran tests and looks fine.
